import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bannerPath = path.join(root, "src/userscript.meta.js");
const hudPath = path.join(root, "src/hud.js");
const outPath = path.join(root, "rg_hud.user.js");

const GENERATED_NOTE = [
  "",
  "// Generated from src/. Do not edit this file by hand.",
  "// Rebuild with: node scripts/build-hud.mjs",
  "",
].join("\n");

const BUNDLE_MODULES = [
  "src/shared/nickname-color.js",
  "src/name-forge/constants.js",
  "src/name-forge/storage.js",
  "src/name-forge/art.js",
  "src/name-forge/paint.js",
  "src/name-forge/raw.js",
  "src/name-forge/markup.js",
  "src/name-forge/index.js",
];

function stripModuleSyntax(source) {
  return source
    .replace(/^import[\s\S]*?from\s+["'][^"']+["'];\n+/gm, "")
    .replace(/^export /gm, "");
}

function extractBootAtlasBody(hudSource) {
  const startMarker = "export function bootAtlas() {\n    'use strict';\n\n";
  const start = hudSource.indexOf(startMarker);
  if (start < 0) throw new Error("missing bootAtlas wrapper in src/hud.js");
  const end = hudSource.lastIndexOf("\n}");
  if (end < start) throw new Error("unterminated bootAtlas in src/hud.js");
  return hudSource.slice(start + startMarker.length, end);
}

export function buildHudSource() {
  const banner = readFileSync(bannerPath, "utf8").trimEnd();
  const modules = BUNDLE_MODULES.map((relative) => {
    const source = stripModuleSyntax(readFileSync(path.join(root, relative), "utf8"));
    return `// ${relative}\n${source.trimEnd()}`;
  });
  const hudBody = extractBootAtlasBody(readFileSync(hudPath, "utf8"));
  return [
    banner,
    GENERATED_NOTE,
    "(function () {",
    "    'use strict';",
    "",
    modules.join("\n\n"),
    "",
    hudBody.trimEnd(),
    "",
    "})();",
    "",
  ].join("\n");
}

export function writeHudBundle(destination = outPath) {
  mkdirSync(path.dirname(destination), { recursive: true });
  const source = buildHudSource();
  writeFileSync(destination, source);
  return { destination, bytes: Buffer.byteLength(source) };
}

const invokedDirectly = process.argv[1]
  && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  const { destination, bytes } = writeHudBundle();
  console.log(`wrote ${path.relative(root, destination)} (${bytes} bytes)`);
}
